config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions do
    collection do
      get 'logout'
    end
  end

  resources :users

  resources :challenges do
    resources :participations
  end

  root 'home#index'
  

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base

	has_many :participations
	has_many :users, through: :participations

	paginates_per 10

	scope :expired, -> { where("expires_at < ?", Time.now) }
	scope :running, -> { where("expires_at >= ?", Time.now) }

	scope :above_points, ->(min_points) { where("points > ?", min_points) }

end

app/models/participation.rb
class Participation < ActiveRecord::Base

	belongs_to :challenge
	belongs_to :user

	validates :challenge_id, presence: true, uniqueness: { scope: :user_id }
	validates :user_id, presence: true

	after_create :give_points_to_user
	

	def give_points_to_user
		user.points += challenge.points
		user.save
	end

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	include BCrypt

	has_many :participations
	has_many :challenges, through: :participations

	paginates_per 10

	def avatar_url
		"http://www.gravatar.com/avatar/4156423#{id}?d=monsterid&s=50"
	end

	def password
	    @password ||= Password.new(password_hash)
	end

	def password=(new_password)
	    @password = Password.create(new_password)
	    self.password_hash = @password
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
  	redirect_to new_session_path unless current_user
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge

    @challenges = @challenges.running if params[:running]
    @challenges = @challenges.expired if params[:expired]
    @challenges = @challenges.above_points(params[:above_points].to_i) if params[:above_points]

    @challenges = @challenges.page(params[:page])
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @participations = @challenge.participations.to_a
    @participation  = @challenge.participations.new
    @users = @challenge.users
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:title, :description, :expires_at, :points)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end

end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@challenge = Challenge.find(params[:challenge_id])
		@participation = @challenge.participations.new(participation_params)
		@participation.user_id = current_user.id
		if @participation.save
			redirect_to @participation.challenge, notice: 'Participation was successfully updated.'
		else
			render text: 'Error !'
		end
	end

	private

	def participation_params
		params.require(:participation).permit(:user_id, :message)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	
	def create
		@user = User.where(email: params[:email]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			redirect_to root_url
		else
			redirect_to new_session_path
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @challenges = @user.challenges
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = params[:password]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/_challenge.html.erb
<div class="challenge">
	<h3><%= link_to challenge.title, challenge %> - <%= challenge.points %> pts</h3>
	<p>
		<%= challenge.description %>
	</p>
</div>

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :expires_at %><br>
    <%= f.datetime_select :expires_at %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/_participations.html.erb
<h2>Participations</h2>
<ul>
	<%= render @participations %>
</ul>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<h1>Listing challenges</h1>

<%= paginate @challenges %>
<%= render @challenges %>
<%= paginate @challenges %>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @challenge %>

<p>
  <strong>Expires at:</strong>
  <%= @challenge.expires_at.strftime("%d %b %Y") %>
</p>


<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

<hr>
<h2>Participants</h2>
<%= render @users %>

<div class="clearfix"></div>

<hr>
<%= render 'participations' %>

<% if current_user %>
	<hr>

	<h2>New participation</h2>
	<%= render 'participations/form' %>
<% end %>

app/views/home/index.html.erb
<h1>Challenge your friends !</h1>

<ul>
	<li><%= link_to 'running challenges', challenges_path(:running => true) %></li>
	<li><%= link_to 'expired challenges', challenges_path(:expired => true) %></li>
	<li><%= link_to 'high point challenges', challenges_path(:above_points => 50) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		Welcome, <%= current_user.name %>
		|
		<%= link_to "logout", logout_sessions_path %>
	<% else %>
		<%= link_to "login", new_session_path %>
	<% end %>
	<hr>

	<%= yield %>

</body>
</html>

app/views/participations/_form.html.erb
<%= form_for [@challenge, @participation] do |f| %>
	
	<%= f.text_area :message %>
	<br>
	<%= f.submit %>

<% end %>

app/views/participations/_participation.html.erb
<li>
	<p><%= link_to participation.user.name, participation.user %></p>
	<p><%= participation.message %></p>
</li>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= text_field_tag "password", '', placeholder: "password" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="user">
	<h3><%= link_to user.name, user %></h3>
	<img src="<%= user.avatar_url %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= paginate @users %>
<%= render @users %>
<%= paginate @users %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<hr>

<h2>His challenges</h2>
<%= render @challenges %>